adding classify unit test files
cnvrg/pose-detection-blueprint pull request #12
Opened 2023-02-01 14:36 UTC by madhuintel

2023-02-03 15:10 UTC, orionsBeltWest requested changes

2023-02-03 15:10 UTC, orionsBeltWest commented on classify/pose_classify.py
>  # Define the model
I see a big chunk of global code and wondering if this could be tucked into some function say model_init or even main?

2023-02-03 15:10 UTC, orionsBeltWest commented on classify/unittest_classify.py
> +        X, y, class_names, _ = pose_classify.load_pose_landmarks(self.train_data)
Also please add test cases to check values within expected range.

2023-02-09 14:27 UTC, madhu-md commented on classify/unittest_classify.py
> +        X, y, class_names, _ = pose_classify.load_pose_landmarks(self.train_data)
@orionsBeltWest As requested, I have made changes and update the PR. Please take a look at your convenience and update me if anything is needed.

2023-02-09 19:46 UTC, orionsBeltWest approved these changes

2023-02-10 15:49 UTC, merged